spring.application.name=gestion-talleres
spring.datasource.url=jdbc:postgresql://localhost:5433/taller2r_db
spring.datasource.username=admin
spring.datasource.password=adminpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
